# Generated by Django 3.2.16 on 2022-11-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycompanyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name': 'Inquiries'},
        ),
    ]
