# Generated by Django 3.2.16 on 2022-11-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycompanyapp', '0002_alter_inquiry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name': 'Inquirie'},
        ),
    ]
